version: '3.4'
services:
  mongo:
    image: "mongo"
    ports:
     - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: happy2code
    volumes:
      - ./data/mongo:/data/db
    command: --auth
  api:
    build:
      context: ./
      args:
        - NODE_ENV=development
    command: /bin/bash -c "yarn run dev"
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://admin:happy2code@mongo:27017/api-starter?authSource=admin
    volumes:
      - ./:/opt/app
      - api:/opt/app/node_modules
    depends_on:
      - mongo 

volumes:
  api:
