version: '3.4'
services:
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: superAdmin
      MONGO_INITDB_ROOT_PASSWORD: 24zYtfint0I0SxTgQn92Ub4NqFJycLu9bdNpsy1FPr0wVkMFGs
    volumes:
      - ./data/mongo:/data/db
    command: --auth
  api:
    build:
      context: ./
      args:
        - NODE_ENV=production
    command: /bin/bash -c "yarn run start"
    ports:
      - "80:3000"
    restart: always
    environment:
      - MONGODB_URL=mongodb://superAdmin:24zYtfint0I0SxTgQn92Ub4NqFJycLu9bdNpsy1FPr0wVkMFGs@mongo:27017/api-starter?authSource=admin
    volumes:
      - ./:/opt/app
      - api:/opt/app/node_modules
    depends_on:
      - mongo

volumes:
  api:
